name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: WebSocketServer

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Lint server files
        run: npx eslint . || echo "Lint errors detected (but not gonna fail build yet)"

      - name: Start server in background
        run: |
          node server.js &
          sleep 5

      - name: WebSocket Client Test
        run: |
          npm install ws
          node ./tests/websocket-test.js

      - name: Firebase Admin SDK Test   
        run: |
          node ./tests/firebase-test.js

      - name: Kill background server
        run: |
          pkill -f "node server.js" || true
